funlab/web/views/accounts.py
import datetime
import mongoengine as me

from flask import (
    Blueprint,
    render_template,
    url_for,
    redirect,
    request,
    session,
    current_app,
    send_file,
    abort,
)
from flask_login import login_user, logout_user, login_required, current_user

from funlab.models import users
from .. import oauth2
from .. import acl
from .. import forms

module = Blueprint("accounts", __name__)


@module.route("/login", methods=["GET", "POST"])
def login():
    form = forms.LoginForm()
    if not form.validate_on_submit():
        error_msg = form.errors
        print(form.errors)
        return render_template("accounts/login.html", form=form)

    user = users.User.objects(username=form.username.data).first()

    if not user or not user.check_password(form.password.data):
        print(form.errors)
        error_msg = "โปรดตรวจสอบ username และ password ของท่าน"
        return render_template("accounts/login.html", form=form, error_msg=error_msg)

    if user.status == "disactive":
        print(form.errors)
        error_msg = "username ของท่านถูกลบออกจากระบบ"
        return render_template("accounts/login.html", form=form, error_msg=error_msg)

    login_user(user)
    user.last_login_date = datetime.datetime.now()
    user.save()
    next = request.args.get("next")
    if next:
        return redirect(next)

    return redirect(url_for("site.index"))


@module.route("/register", methods=["GET", "POST"])
def register():
    form = forms.accounts.RegisterForm()
    if not form.validate_on_submit():
        return render_template("accounts/register.html", form=form)
    user = users.User.objects(username=form.username.data)
    if user:
        error_msg = "Username นี้ถูกใช้งานแล้ว"
        return render_template("accounts/register.html", form=form, error_msg=error_msg)
    user = users.User.objects(email=form.email.data)
    if user:
        error_msg = "Email นี้ถูกใช้งานแล้ว"
        return render_template("accounts/register.html", form=form, error_msg=error_msg)
    user = users.User()
    form.populate_obj(user)
    user.set_password(form.input_password.data)
    user.save()
    return redirect(url_for("accounts.login", messages="success"))


@module.route("/login/<name>")
def login_oauth(name):
    client = oauth2.oauth2_client

    scheme = request.environ.get("HTTP_X_FORWARDED_PROTO", "http")
    redirect_uri = url_for(
        "accounts.authorized_oauth", name=name, _external=True, _scheme=scheme
    )
    response = None
    if name == "google":
        response = client.google.authorize_redirect(redirect_uri)
    elif name == "facebook":
        response = client.facebook.authorize_redirect(redirect_uri)
    elif name == "line":
        response = client.line.authorize_redirect(redirect_uri)

    elif name == "psu":
        response = client.psu.authorize_redirect(redirect_uri)
    elif name == "engpsu":
        response = client.engpsu.authorize_redirect(redirect_uri)
    return response


@module.route("/auth/<name>")
def authorized_oauth(name):
    client = oauth2.oauth2_client
    remote = None
    try:
        if name == "google":
            remote = client.google
        elif name == "facebook":
            remote = client.facebook
        elif name == "line":
            remote = client.line
        elif name == "psu":
            remote = client.psu
        elif name == "engpsu":
            remote = client.engpsu

        token = remote.authorize_access_token()

    except Exception as e:
        print("autorize access error =>", e)
        return redirect(url_for("accounts.login"))

    session["oauth_provider"] = name
    return oauth2.handle_authorized_oauth2(remote, token)


@module.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("site.index"))

funlab/web/views/dashboard.py
import datetime
import mongoengine as me

from flask import (
    Blueprint,
    render_template,
    url_for,
    redirect,
    request,
    session,
    current_app,
    send_file,
    abort,
)
from flask_login import login_user, logout_user, login_required, current_user

from funlab.models import users
from .. import oauth2
from .. import acl
from .. import forms

module = Blueprint("dashboard", __name__, url_prefix="/dashboard")


@module.route("/")
def index():
    return render_template("dashboard/index.html")

funlab/web/views/sites.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import current_user

module = Blueprint("site", __name__)


@module.route("/")
def index():
    return render_template('/site/index.html')

funlab/web/templates/base/banner.html
<div class="ui inverted vertical center aligned segment">
    <div class="ui text container">
      <div>
        {#<img width="300px" src="{{ url_for('static', filename='images/lotus-500px.png') }}"#}
        <i class="ui icon poo massive" ></i>
      </div> 
      <h1 class="ui huge inverted header" style="font-size:4em">{{ config.get('APP_TITLE') }} </h1>
      <h2>Funlab web test, Please Login.</h2>
      <div style="padding: 5vh;">
        Funlab web test 101
      </div>
    </div>
</div>

funlab/web/templates/base/base-layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
    <title>{% block title  %}{{ config.get('APP_TITLE') }}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='node_modules/fomantic-ui-css/semantic.min.css') | add_date_url}}">
    <script src="{{ url_for('static', filename='node_modules/jquery/dist/jquery.min.js') | add_date_url}}"></script>
    <script src="{{ url_for('static', filename='node_modules/fomantic-ui-css/semantic.min.js') | add_date_url}}"></script>
    <style type="text/css">
      body {
        background-color: #DADADA;
      }
    </style>
    
    {% block default_head %}{% endblock %}
    {% block additional_head %}{% endblock %}
  </head>

  <body>
    {% block body %}{% endblock %}
  </body>
	{% block additional_js %}{% endblock %}
</html>

funlab/web/templates/base/default-page.html
{% extends "/base/base-layout.html" %}
{% block body %}
<header>
{% block header %}
  {% include "/base/toolbar.html" %}
  {% if request.path == '/' %}
    {% include "/base/banner.html" %}
  {% else %}
    <div style="padding-top:50px;"></div>
  {% endif %}
{% endblock %}
</header>

<main>
  <div class="container">
    {% block content %}{% endblock content %}
  </div>
</main>

{#<footer class="ui vertical footer segment" style="padding-top: 2em;">
{% include "/base/footer.html" %}
</footer>#}
{% endblock %}

funlab/web/templates/base/footer.html
<div class="ui container">
    <div class="ui grid">
      <div class="four wide column">
        <h5 class="ui header">Funlab web test</h5>
        <img width="20%" src="{{ url_for('static', filename='images/r202.png') }}">
        <p>Develop by R202 research lab</p>
      </div>
      <div class="five wide column">
        <h5 class="ui header">Department of Computer Engineering</h5>
        <p>
        Faculty of Engineering<br/>
        Prince of Songkla University<br/>
        Hat Yai, Thailand
        </p>
      </div>
      <div class="seven wide column">
        <h5 class="ui header">Connect</h5>
        <div class="ui link list">
          <a href="http://coe.psu.ac.th">CoE, Eng, PSU</a>
        </div>
      </div>
    </div>
  </div>

funlab/web/templates/base/toolbar.html
<div class="ui fixed inverted menu">
    <div class="ui container">
      <a href="{{ url_for('site.index') }}" class="header item">
        {# <img class="logo" src="{{ url_for('static', filename='images/sadhu.png') }}"> #}
        <i class="ui icon poo"></i>
        <span style="padding-left:10px;">
          {{ config['APP_TITLE'] }}
        </span>
      </a>
      {#
      <a href="{{ url_for('dashboard.index') }}" class="item">Dashboard</a>
      <div class="ui simple dropdown item">
        Dropdown <i class="dropdown icon"></i>
        <div class="menu">
          <a class="item" href="#">Link Item</a>
          <a class="item" href="#">Link Item</a>
          <div class="divider"></div>
          <div class="header">Header Item</div>
          <div class="item">
            <i class="dropdown icon"></i>
            Sub Menu
            <div class="menu">
              <a class="item" href="#">Link Item</a>
              <a class="item" href="#">Link Item</a>
            </div>
          </div>
          <a class="item" href="#">Link Item</a>
        </div>
      </div>
      #}
      <div class="right menu">
        {#
        <div class="item">
          <div class="ui transparent inverted icon input">
            <i class="search icon"></i>
            <input type="text" placeholder="Search">
          </div>
        </div>
        #}
      {% if current_user.is_authenticated %}
        <a class="item" href="{{ url_for('dashboard.index') }}">Dashboard</a>
        <a class="item" href="{{ url_for('accounts.logout') }}">Logout</a>
      {% else %}
        <a class="item" href="{{ url_for('accounts.login') }}">Login</a>
      {% endif %}
  
      </div>
    </div>
  </div>
  <div style="padding-top: 40px;"> </div>